# Generated by Django 6.0.5 on 2026-05-09 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('project_manager', 'Руководитель проекта'), ('implementer', 'Внедренец'), ('engineer', 'Инженер'), ('guest', 'Гость')], default='guest', max_length=30, verbose_name='Роль')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
