# Generated by Django 6.0.5 on 2026-05-09 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название ПО')),
                ('description', models.TextField(blank=True, verbose_name='Описание ПО')),
            ],
            options={
                'verbose_name': 'Программное обеспечение',
                'verbose_name_plural': 'Программное обеспечение',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField(verbose_name='Дата обновления')),
                ('version', models.CharField(max_length=100, verbose_name='Версия')),
                ('changes_description', models.TextField(verbose_name='Описание изменений')),
                ('update_reason', models.TextField(blank=True, verbose_name='Причина обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_updates', to='projects.project', verbose_name='Проект')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='software_updates', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Обновление ПО',
                'verbose_name_plural': 'История обновлений ПО',
                'ordering': ['-update_date'],
            },
        ),
    ]
