# Generated by Django 6.0.5 on 2026-05-09 10:43

import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория документа',
                'verbose_name_plural': 'Категории документов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=documents.models.project_document_upload_path, verbose_name='Файл')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Исходное имя файла')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documentcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Документ проекта',
                'verbose_name_plural': 'Документы проекта',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
