# Generated by Django 6.0.5 on 2026-05-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_type', models.CharField(choices=[('board', 'Плата'), ('camera', 'Камера'), ('switch', 'Коммутатор'), ('power_supply', 'БП')], max_length=30, verbose_name='Тип')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('status', models.CharField(choices=[('free', 'Свободно'), ('ordered', 'Заказ'), ('reserved', 'Бронь'), ('attached', 'Привязано')], default='free', max_length=30, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Оборудование производства',
                'verbose_name_plural': 'Оборудование производства',
                'ordering': ['production_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(choices=[('detector', 'Детектор'), ('server', 'Сервер')], max_length=30, verbose_name='Тип оборудования')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('cameras_per_detector', models.PositiveIntegerField(blank=True, null=True, verbose_name='Камер на детектор')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Оборудование проекта',
                'verbose_name_plural': 'Оборудование проекта',
                'ordering': ['equipment_type', 'name'],
            },
        ),
    ]
