# Generated by Django 6.0.5 on 2026-05-09 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('company_type', models.CharField(choices=[('final_customer', 'Конечный заказчик'), ('contract_customer', 'Заказчик по договору'), ('partner', 'Партнёр'), ('other', 'Другое')], default='other', max_length=30, verbose_name='Тип компании')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название статуса')),
                ('color', models.CharField(default='#6c757d', help_text='Например: #28a745', max_length=30, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Статус проекта',
                'verbose_name_plural': 'Статусы проектов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название тега')),
            ],
            options={
                'verbose_name': 'Тег проекта',
                'verbose_name_plural': 'Теги проектов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Дата поставки')),
                ('active_software_version', models.CharField(blank=True, max_length=100, verbose_name='Активная версия ПО')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Бюджет проекта')),
                ('password_manager_link', models.URLField(blank=True, verbose_name='Ссылка на менеджер паролей')),
                ('goal', models.TextField(blank=True, verbose_name='Цель проекта')),
                ('situation_description', models.TextField(blank=True, verbose_name='Описание ситуации')),
                ('boundaries', models.TextField(blank=True, verbose_name='Границы проекта')),
                ('limitations', models.TextField(blank=True, verbose_name='Ограничения')),
                ('key_metrics', models.TextField(blank=True, verbose_name='Ключевые метрики')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.city', verbose_name='Город')),
                ('contract_customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_customer_projects', to='projects.company', verbose_name='Заказчик по договору')),
                ('final_customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final_customer_projects', to='projects.company', verbose_name='Конечный заказчик')),
                ('implementer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='implemented_projects', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный за внедрение')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
    ]
